### ISSUE TITLE
POST 'serve-file' : error 400

### ISSUE THREAD

**Issue by Cart3sianBear** [cerndb/dbod-web#97]
![untitled](https://user-images.githubusercontent.com/22033714/44328872-196b9a80-a463-11e8-95a9-601d3d50f07d.png)

**Comment by icot** [comment]
The serve-file was incorrectly defined in Rundeck as to run locally.
After fixing that it works as expected, but need to verify through the pipeline

**Comment by icot** [comment]
Additionally, there were at least two things wrong with the current implementation:
- The web app was doing the wrong requests, The format should be:
```
'{"options":{"filepath":"/tmp/kk"}}'
```
- The server was incorrectly threating the original request body and corrupting it on the forwarding to the Rundeck API

**Comment by icot** [comment]
Additionally, the return of the server launch will be in the "log" attribute of the JSON object, in the following format, which needs to be used for the actual file download:
```
<host:port>
```
